# Generated by Django 3.0.3 on 2020-03-04 03:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cuenta', max_length=20)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 3, 4))),
                ('concept', models.CharField(default='Movimiento', max_length=20)),
                ('detail', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='$', max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finper.Account', verbose_name='cuenta_del_movimiento')),
            ],
        ),
    ]
