# Generated by Django 3.0.3 on 2020-03-04 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finper', '0002_auto_20200304_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 3, 45, 5, 509890, tzinfo=utc)),
        ),
    ]
