# Generated by Django 3.0.3 on 2020-03-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finper', '0004_auto_20200304_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='amount',
            new_name='amount_in',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='account',
        ),
        migrations.AddField(
            model_name='movement',
            name='account_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account_in', to='finper.Account', verbose_name='cuenta_de_entrada'),
        ),
        migrations.AddField(
            model_name='movement',
            name='account_out',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account_out', to='finper.Account', verbose_name='cuenta_de_salida'),
        ),
        migrations.AddField(
            model_name='movement',
            name='amount_out',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finper.Category', verbose_name='categoría_del_movimiento'),
        ),
    ]
