# Generated by Django 3.0.3 on 2020-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finper', '0005_auto_20200304_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='amount_in',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='amount_out',
        ),
        migrations.AddField(
            model_name='movement',
            name='direction',
            field=models.CharField(choices=[('+', 'Entrada'), ('-', 'Salida'), ('=', 'Traspaso')], default='=', max_length=1),
        ),
    ]
