# Generated by Django 3.0.3 on 2020-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finper', '0006_auto_20200305_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='direction',
            field=models.CharField(choices=[('+', 'Entrada'), ('-', 'Salida'), ('=', 'Traspaso')], max_length=1),
        ),
    ]
