# Generated by Django 3.0.3 on 2020-03-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finper', '0007_auto_20200307_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='account_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='finper.Account', verbose_name='cuenta_de_entrada'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='account_out',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='finper.Account', verbose_name='cuenta_de_salida'),
        ),
    ]
